apiVersion: apps/v1
kind: Deployment
metadata:
  name:  kubedemo
  namespace: default
  labels:
    app:  kubedemo
spec:
  selector:
    matchLabels:
      app: kubedemo
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  kubedemo
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  kubedemo
        image:  kumarbitwise/kubedemo:4.0.0

        env:
          - name: password
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password

        envFrom:
          - configMapRef:
              name: kubedemo-config

        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /get
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        # env:
        # - name: DB_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: MYAPP
        #       key: DB_HOST
        ports:
        - containerPort:  8080
          name:  kubedemo
      #   volumeMounts:
      #   - name: localtime
      #     mountPath: /etc/localtime
      # volumes:
      #   - name: localtime
      #     hostPath:
      #       path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always